project_id = "jtlelokzpqkgvlwomfus"

[functions.consulta-cnpj]
verify_jwt = false

[functions.import-clients]
verify_jwt = false

[functions.ingest-sharepoint-file]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true