
ALTER TYPE app_role ADD VALUE IF NOT EXISTS 'COMERCIAL';
ALTER TYPE app_role ADD VALUE IF NOT EXISTS 'JURIDICO';
ALTER TYPE app_role ADD VALUE IF NOT EXISTS 'MARKETING';
ALTER TYPE app_role ADD VALUE IF NOT EXISTS 'RH';
