-- 1. Adiciona IDENTITY ao id da staging (BY DEFAULT permite insert explícito se um dia precisar)
ALTER TABLE public.raw_comissoes_historico_staging
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Adiciona PK na staging (espelha prod)
ALTER TABLE public.raw_comissoes_historico_staging
  ADD CONSTRAINT raw_comissoes_historico_staging_pkey PRIMARY KEY (id);

-- 3. Recria swap com: INSERT colunar (sem id), comentários explicativos e RAISE NOTICE estruturados
CREATE OR REPLACE FUNCTION public.rpc_sync_cursor_complete_swap(
  p_sync_name text, p_claim uuid, p_target_table text, p_staging_table text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_count_staging bigint;
  v_owns boolean;
BEGIN
  -- Valida claim do worker
  SELECT EXISTS (
    SELECT 1 FROM public.sync_cursor
     WHERE sync_name = p_sync_name AND claimed_by = p_claim
  ) INTO v_owns;

  IF NOT v_owns THEN
    RAISE EXCEPTION 'Claim inválido para %', p_sync_name;
  END IF;

  -- Whitelist: só permite o par esperado de tabelas
  IF p_target_table NOT IN ('raw_comissoes_historico')
     OR p_staging_table NOT IN ('raw_comissoes_historico_staging') THEN
    RAISE EXCEPTION 'Tabela não permitida no swap: % ← %', p_target_table, p_staging_table;
  END IF;

  EXECUTE format('SELECT count(*) FROM public.%I', p_staging_table) INTO v_count_staging;

  -- Log estruturado de início (aparece em pg_log)
  RAISE NOTICE 'swap_started: target=%, staging_rows=%', p_target_table, v_count_staging;

  -- Defesa em profundidade: prod não tem triggers hoje, mas se algum trigger for
  -- adicionado no futuro (ex: refresh MV por linha), ele causaria N refreshes
  -- durante o INSERT em massa. DISABLE garante 1 refresh único no fim via refreshMV().
  EXECUTE format('ALTER TABLE public.%I DISABLE TRIGGER ALL', p_target_table);

  -- Swap atômico: TRUNCATE + INSERT na MESMA transação implícita do PL/pgSQL.
  -- Se o INSERT falhar, o TRUNCATE sofre rollback automaticamente — prod não fica vazia.
  EXECUTE format('TRUNCATE TABLE public.%I', p_target_table);

  -- INSERT colunar EXPLÍCITO (sem id): a coluna id da prod é GENERATED ALWAYS AS IDENTITY,
  -- então não pode receber valor explícito. Deixamos a identity do prod gerar IDs novos.
  EXECUTE format(
    'INSERT INTO public.%I (data, ingested_at, mes_ano)
       SELECT data, ingested_at, mes_ano FROM public.%I',
    p_target_table, p_staging_table
  );

  EXECUTE format('ALTER TABLE public.%I ENABLE TRIGGER ALL', p_target_table);

  -- Limpa staging após swap bem-sucedido
  EXECUTE format('TRUNCATE TABLE public.%I', p_staging_table);

  -- Log estruturado de fim
  RAISE NOTICE 'swap_completed: target=%, inserted=%', p_target_table, v_count_staging;

  -- Marca cursor como completed
  UPDATE public.sync_cursor
     SET status = 'completed',
         completed_at = now(),
         claimed_by = NULL,
         claimed_until = NULL,
         error = NULL,
         updated_at = now()
   WHERE sync_name = p_sync_name;

  RETURN jsonb_build_object('swapped', true, 'rows', v_count_staging);
END;
$function$;

-- 4. Reset do cursor para nova tentativa
UPDATE public.sync_cursor
   SET status='pending',
       next_window_start=2,
       total_rows_seen=0,
       total_rows_target=NULL,
       attempts=0,
       error=NULL,
       claimed_by=NULL,
       claimed_until=NULL,
       last_heartbeat=now(),
       started_at=now(),
       completed_at=NULL,
       updated_at=now()
 WHERE sync_name='historico_completo';